# -*- conf -*-

shell=/usr/bin/fish
app-id=terminal # globally set wayland app-id. Default values are "foot" and "footclient" for desktop and server mode
title=foot
locked-title=yes

font=JetBrains Mono NF:size=11
box-drawings-uses-font-glyphs=no
[main]
include =~/.cache/wal/colors-foot.ini

[desktop-notifications]
command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}

[scrollback]
lines=100000

[key-bindings]
clipboard-copy=Control+c XF86Copy
clipboard-paste=Control+v XF86Paste

[search-bindings]
cancel=Control+g Control+Shift+c Escape

[url-bindings]
cancel=Control+g Control+Shift+c Control+d Escape

